### ISSUE TITLE
Optimize recommendations in YouTube home page

### ISSUE THREAD

**Issue by lenhoanglnh** [tournesol-app/tournesol-chrome-extension#8]
An easy fix would be to add random noise to make recommendations more diverse.
In the longer run, we should think about how to optimize this (perhaps by looking at YouTube recommends before making recommendations?).

@lfaucon the current scores are not the same as on https://tournesol.app/recommendations. What did you use? 
Maybe document this in the wiki?

**Comment by BenCrulis** [comment]
It seems you are already using a computation to get the Pareto front of the videos according to their multiple score (it is called the Skyline operator for database people).
Since there are many different kinds of scores for videos, the Pareto front should be quite big, I think. Thus if we go for this method, we need to have a way to reduce the number of points sampled from the Pareto front. One of the objective could be keeping good diversity in the final recommended point set.

I know of a few ways that can be used to "prune" the Pareto optimal solutions until we have only a few key videos while keeping sufficient diversity:
- one way is to use a crowding distance based sorting and then truncation as used in the NSGA-II optimization heuristic. see: https://www.iitk.ac.in/kangal/Deb_NSGA-II.pdf
- you can also compute `k` references direction using a method called Riesz s-energy and then select the closest Pareto optimal solution to each reference direction. see https://pymoo.org/misc/reference_directions.html
- alternatively, you can compute a point called the utopia point, which is the vector whose components is the minimum of each score dimension. This point can then be used to compute proximity, angles...
- Pareto front can have weird shapes, which can be bad for picking really diverse points. It could be useful to estimate a norm which gives a length of 1 to all points of the Pareto front, and then you can use this norm to create a metric which can both be utilized to compute proximity to the utopia point, and to compute distance between neighbors. See AGE-MOEA algorithm which does this: https://www.researchgate.net/publication/332833497_An_Adaptive_Evolutionary_Algorithm_based_on_Non-Euclidean_Geometry_for_Many-objective_Optimization

In all cases, it could be necessary to normalize the space around the Pareto front beforehand. To do this you need to compute the utopia point and a point called the nadir point, which is computed like the utopia point, but with the max of the scores of the Pareto optimal solutions. Then you do a min-max normalization for each dimension independently.

Maybe you are already doing that, but as a side note, you could use the time since a video was released as one of the scores, which should be minimized. This way videos that are a bit old but still very good would have a chance stay longer in the recommended video set.

Let me know what you think of my suggestions!

**Comment by lfaucon** [comment]
@lenhoanglnh the scores were different because I mistyped the weight for `better_habits` from `100` to `1000`. This is now fixed. I also added that the extension queries 12 videos and picks 4 uniformily at random. More discussions and ideas for optimizing recommendations are still welcome :)

**Comment by lenhoanglnh** [comment]
I would suggest to draw the first two videos randomly among the top 30 videos of all time, and the third video among the top 20 videos of the previous month and the fourth video among the top 10 of the last week, especially right now.

This is a matter of safety. We don't want to be recommending poorly rated videos.

(Also, ideally, the computation of the top videos should be made by the backend, say, once a day... but I guess this should be left for future work)

**Comment by lfaucon** [comment]
To minimize the number of API calls, I would recommend 
2 out of top 30 more than 21 days old and 2 out of top 10 less than 21 days old

**Comment by lfaucon** [comment]
This is now implemented. Will be deployed out with version 1.6
